server.port=9091

		## Un comment for H2 database ##
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

		## PgAdmin Database ##
		
spring.datasource.url=jdbc:postgresql://localhost:5432/simplestcrud
spring.datasource.username=postgres
spring.datasource.password=1608
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect



spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto= update
spring.h2.console.enabled=true
hibernate.dialect=org.hibernate.dialect.H2Dialect
# default path: h2-console
#spring.h2.console.path=/h2-ui


