spring.application.name=spring-mcp
spring.ai.mcp.server.name=syed
spring.ai.mcp.server.version=0.1.1


#MCP server configurations
spring.ai.mcp.server.protocol=streamable
spring.ai.mcp.server.stdio=false
spring.ai.mcp.server.type=sync

server.port=9090
